import {
  Connection,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { Program, AnchorProvider, BN, Idl } from "@coral-xyz/anchor";
import { useCallback, useEffect, useState } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";

// ─── Program ID ──────────────────────────────────────────────────────────────

export const PROGRAM_ID = new PublicKey(
  "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
);

// ─── IDL (inlined — generated by `anchor build`) ─────────────────────────────

export const IDL: Idl = {
  version: "0.1.0",
  name: "attention_market",
  instructions: [
    {
      name: "createMarket",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "authority", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "contentId", type: "string" },
        { name: "title", type: "string" },
        { name: "durationSeconds", type: "i64" },
      ],
    },
    {
      name: "placeBet",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "bet", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "outcome", type: "u8" },
        { name: "amountLamports", type: "u64" },
      ],
    },
    {
      name: "resolveMarket",
      accounts: [
        { name: "market", isMut: true, isSigner: false },
        { name: "authority", isMut: false, isSigner: true },
      ],
      args: [{ name: "winningOutcome", type: "u8" }],
    },
    {
      name: "claimWinnings",
      accounts: [
        { name: "market", isMut: false, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "bet", isMut: true, isSigner: false },
        { name: "user", isMut: true, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "Market",
      type: {
        kind: "struct",
        fields: [
          { name: "contentId", type: "string" },
          { name: "title", type: "string" },
          { name: "authority", type: "publicKey" },
          { name: "totalViral", type: "u64" },
          { name: "totalFlop", type: "u64" },
          { name: "endTime", type: "i64" },
          { name: "resolved", type: "bool" },
          { name: "outcome", type: "u8" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "BetRecord",
      type: {
        kind: "struct",
        fields: [
          { name: "market", type: "publicKey" },
          { name: "user", type: "publicKey" },
          { name: "outcome", type: "u8" },
          { name: "amount", type: "u64" },
          { name: "claimed", type: "bool" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "ContentIdTooLong", msg: "Content ID exceeds 64 characters" },
    { code: 6001, name: "TitleTooLong", msg: "Title exceeds 128 characters" },
    { code: 6002, name: "InvalidDuration", msg: "Duration must be positive" },
    { code: 6003, name: "InvalidOutcome", msg: "Outcome must be 1 (viral) or 2 (flop)" },
    { code: 6004, name: "InvalidAmount", msg: "Amount must be greater than zero" },
    { code: 6005, name: "MarketAlreadyResolved", msg: "Market has already been resolved" },
    { code: 6006, name: "MarketExpired", msg: "Market betting period has expired" },
    { code: 6007, name: "MarketNotExpired", msg: "Market has not yet expired" },
    { code: 6008, name: "MarketNotResolved", msg: "Market has not been resolved yet" },
    { code: 6009, name: "AlreadyClaimed", msg: "Winnings already claimed" },
    { code: 6010, name: "DidNotWin", msg: "Your bet did not win" },
    { code: 6011, name: "NoWinners", msg: "No winners on the winning side" },
    { code: 6012, name: "Overflow", msg: "Arithmetic overflow" },
  ],
};

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MarketAccount {
  publicKey: PublicKey;
  contentId: string;
  title: string;
  authority: PublicKey;
  totalViral: BN;
  totalFlop: BN;
  endTime: BN;
  resolved: boolean;
  outcome: number;
  bump: number;
}

export interface BetRecord {
  publicKey: PublicKey;
  market: PublicKey;
  user: PublicKey;
  outcome: number;
  amount: BN;
  claimed: boolean;
  bump: number;
}

export interface MarketOdds {
  viralPercent: number;
  flopPercent: number;
  totalSOL: number;
}

export type BetSide = "viral" | "flop";

// ─── PDA helpers ─────────────────────────────────────────────────────────────

export function getMarketPda(contentId: string): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("market"), Buffer.from(contentId)],
    PROGRAM_ID
  );
}

export function getVaultPda(marketPubkey: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), marketPubkey.toBuffer()],
    PROGRAM_ID
  );
}

export function getBetPda(
  marketPubkey: PublicKey,
  userPubkey: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("bet"), marketPubkey.toBuffer(), userPubkey.toBuffer()],
    PROGRAM_ID
  );
}

// ─── Program factory ─────────────────────────────────────────────────────────

function getProgram(connection: Connection, wallet: any): Program {
  const provider = new AnchorProvider(
    connection,
    wallet,
    AnchorProvider.defaultOptions()
  );
  return new Program(IDL, PROGRAM_ID, provider);
}

// ─── SDK functions ────────────────────────────────────────────────────────────

export async function createMarket(
  connection: Connection,
  wallet: any,
  contentId: string,
  title: string,
  durationSeconds: number
): Promise<{ tx: string; marketPubkey: PublicKey }> {
  const program = getProgram(connection, wallet);
  const [marketPda] = getMarketPda(contentId);
  const [vaultPda] = getVaultPda(marketPda);

  const tx = await program.methods
    .createMarket(contentId, title, new BN(durationSeconds))
    .accounts({
      market: marketPda,
      vault: vaultPda,
      authority: wallet.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  return { tx, marketPubkey: marketPda };
}

export async function placeBet(
  connection: Connection,
  wallet: any,
  marketPubkey: PublicKey,
  outcome: BetSide,
  amountSOL: number
): Promise<string> {
  const program = getProgram(connection, wallet);
  const [vaultPda] = getVaultPda(marketPubkey);
  const [betPda] = getBetPda(marketPubkey, wallet.publicKey);
  const outcomeNum = outcome === "viral" ? 1 : 2;
  const lamports = new BN(Math.floor(amountSOL * LAMPORTS_PER_SOL));

  return program.methods
    .placeBet(outcomeNum, lamports)
    .accounts({
      market: marketPubkey,
      vault: vaultPda,
      bet: betPda,
      user: wallet.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .rpc();
}

export async function resolveMarket(
  connection: Connection,
  wallet: any,
  marketPubkey: PublicKey,
  outcome: BetSide
): Promise<string> {
  const program = getProgram(connection, wallet);
  const outcomeNum = outcome === "viral" ? 1 : 2;

  return program.methods
    .resolveMarket(outcomeNum)
    .accounts({
      market: marketPubkey,
      authority: wallet.publicKey,
    })
    .rpc();
}

export async function claimWinnings(
  connection: Connection,
  wallet: any,
  marketPubkey: PublicKey
): Promise<string> {
  const program = getProgram(connection, wallet);
  const [vaultPda] = getVaultPda(marketPubkey);
  const [betPda] = getBetPda(marketPubkey, wallet.publicKey);

  return program.methods
    .claimWinnings()
    .accounts({
      market: marketPubkey,
      vault: vaultPda,
      bet: betPda,
      user: wallet.publicKey,
    })
    .rpc();
}

export async function getMarket(
  connection: Connection,
  marketPubkey: PublicKey
): Promise<MarketAccount | null> {
  const program = getProgram(connection, { publicKey: PublicKey.default } as any);
  try {
    const account = await (program.account as any).market.fetch(marketPubkey);
    return { publicKey: marketPubkey, ...account };
  } catch {
    return null;
  }
}

export async function getMarketByContentId(
  connection: Connection,
  contentId: string
): Promise<MarketAccount | null> {
  const [marketPda] = getMarketPda(contentId);
  return getMarket(connection, marketPda);
}

export async function getUserBet(
  connection: Connection,
  marketPubkey: PublicKey,
  userPubkey: PublicKey
): Promise<BetRecord | null> {
  const program = getProgram(connection, { publicKey: PublicKey.default } as any);
  const [betPda] = getBetPda(marketPubkey, userPubkey);
  try {
    const account = await (program.account as any).betRecord.fetch(betPda);
    return { publicKey: betPda, ...account };
  } catch {
    return null;
  }
}

// ─── Odds calculator ──────────────────────────────────────────────────────────

export function computeOdds(market: MarketAccount | null): MarketOdds {
  if (!market) {
    return { viralPercent: 60, flopPercent: 40, totalSOL: 0 };
  }
  const viral = market.totalViral.toNumber();
  const flop = market.totalFlop.toNumber();
  const total = viral + flop;
  if (total === 0) {
    return { viralPercent: 50, flopPercent: 50, totalSOL: 0 };
  }
  return {
    viralPercent: Math.round((viral / total) * 100),
    flopPercent: Math.round((flop / total) * 100),
    totalSOL: total / LAMPORTS_PER_SOL,
  };
}

// ─── React hook: useMarket ────────────────────────────────────────────────────

export function useMarket(contentId: string) {
  const { connection } = useConnection();
  const wallet = useWallet();

  const [market, setMarket] = useState<MarketAccount | null>(null);
  const [userBet, setUserBet] = useState<BetRecord | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Mock odds that drift over time when program data is unavailable
  const [mockOdds, setMockOdds] = useState({ viralPercent: 60, flopPercent: 40 });

  const [marketPubkey] = getMarketPda(contentId);

  const fetchMarket = useCallback(async () => {
    try {
      const m = await getMarket(connection, marketPubkey);
      setMarket(m);

      if (m && wallet.publicKey) {
        const bet = await getUserBet(connection, marketPubkey, wallet.publicKey);
        setUserBet(bet);
      }
    } catch {
      // Fall back to mock data — market may not exist yet on devnet
    }
  }, [connection, marketPubkey, wallet.publicKey]);

  useEffect(() => {
    fetchMarket();
  }, [fetchMarket]);

  // Drift mock odds every 5 seconds when no real market data
  useEffect(() => {
    if (market) return;
    const interval = setInterval(() => {
      setMockOdds((prev) => {
        const drift = Math.floor(Math.random() * 7) - 3; // -3 to +3
        const viral = Math.min(95, Math.max(5, prev.viralPercent + drift));
        return { viralPercent: viral, flopPercent: 100 - viral };
      });
    }, 5000);
    return () => clearInterval(interval);
  }, [market]);

  const handlePlaceBet = useCallback(
    async (outcome: BetSide, amountSOL: number) => {
      if (!wallet.publicKey || !wallet.signTransaction) {
        throw new Error("Wallet not connected");
      }
      setLoading(true);
      setError(null);
      try {
        // Try to create market first if it doesn't exist
        if (!market) {
          try {
            await createMarket(connection, wallet, contentId, contentId, 300);
          } catch {
            // Already exists or failed — proceed to place bet
          }
        }
        await placeBet(connection, wallet, marketPubkey, outcome, amountSOL);
        await fetchMarket();
      } catch (e: any) {
        setError(e.message ?? "Transaction failed");
        throw e;
      } finally {
        setLoading(false);
      }
    },
    [connection, wallet, market, contentId, marketPubkey, fetchMarket]
  );

  const handleClaimWinnings = useCallback(async () => {
    if (!wallet.publicKey) throw new Error("Wallet not connected");
    setLoading(true);
    setError(null);
    try {
      await claimWinnings(connection, wallet, marketPubkey);
      await fetchMarket();
    } catch (e: any) {
      setError(e.message ?? "Claim failed");
      throw e;
    } finally {
      setLoading(false);
    }
  }, [connection, wallet, marketPubkey, fetchMarket]);

  const handleResolveMarket = useCallback(
    async (outcome: BetSide) => {
      if (!wallet.publicKey) throw new Error("Wallet not connected");
      setLoading(true);
      try {
        await resolveMarket(connection, wallet, marketPubkey, outcome);
        await fetchMarket();
      } finally {
        setLoading(false);
      }
    },
    [connection, wallet, marketPubkey, fetchMarket]
  );

  const odds = market ? computeOdds(market) : { ...mockOdds, totalSOL: 0 };

  return {
    market,
    marketPubkey,
    userBet,
    odds,
    loading,
    error,
    placeBet: handlePlaceBet,
    claimWinnings: handleClaimWinnings,
    resolveMarket: handleResolveMarket,
    refresh: fetchMarket,
  };
}
